language: ruby
rvm:
  - 2.0.0
services:
  - mongodb
env:
  - URL_PREFIX=http://localhost:5000
before_script:
  - "bundle exec rake server:start"
script:
  - "bundle exec rake travis"
after_script:
  - "bundle exec rake server:stop"